var num1=-123;
var num2=24.66;
var num3=337678435;
var num4=4000.00;
var string1="Uma";
var string2="Atul";
var string3="Jha";
var boolean1 = true;
var boolean2 = 1;
var goal;
console.log("The first number is:",num1);
console.log("The second number is:",num2);
console.log("The third number is:",num3);
console.log("The fourth number is:",num4);
console.log("The First String:", string1);
console.log("The Second String:", string1);
console.log("The Third String:", string1);
console.log("The first boolean is:",boolean1);
console.log("The second boolean is:",boolean2);
console.log("The undefined variable is:",goal);